# Generated by Django 4.2 on 2024-09-10 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user_id', models.UUIDField()),
                ('to_user_id', models.UUIDField()),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('accepted', 'Принят')], default='pending', max_length=15)),
            ],
        ),
    ]
