# Generated by Django 4.2 on 2024-09-10 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friendship', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendship',
            unique_together={('from_user_id', 'to_user_id')},
        ),
    ]
