name: Build and Test DEV
on:
  push:
    branches: [dev]
jobs:
  build_and_test_backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build app
        run: docker compose build

      - name: Test app
        run: docker compose up user_service_test posts_service_test