name: Build, Test and Deploy !PRODUCTION!
on:
  push:
    branches: [prod]
env:
  CORS: ${{ secrets.CORS }}
  FRONTEND_DOMAIN: ${{ secrets.FRONTEND_DOMAIN }}
  FRONTEND_PORT: ${{ secrets.FRONTEND_PORT }}
jobs:
  build_test_deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Create .env file
        run: cp configs/.env.prod.example configs/.env.prod

      - name: Build app
        run: > 
          CORS="${{ env.CORS }}"
          FRONTEND_DOMAIN="${{ env.FRONTEND_DOMAIN}}"
          FRONTEND_PORT="${{ env.FRONTEND_PORT }}"
          docker compose --env-file .env.prod build

      - name: Test app
        run: > 
          CORS="${{ env.CORS }}"
          FRONTEND_DOMAIN="${{ env.FRONTEND_DOMAIN}}"
          FRONTEND_PORT="${{ env.FRONTEND_PORT }}"
          docker compose --env-file .env.prod up
          user_service_test

      - name: deploy app
        run: >
          CORS="${{ env.CORS }}"
          FRONTEND_DOMAIN="${{ env.FRONTEND_DOMAIN}}"
          FRONTEND_PORT="${{ env.FRONTEND_PORT }}"
          docker compose --env-file .env.prod up
          user_service vue kong
