name: Build, Test, Deploy
on:
  push:
jobs:
  prepare-env:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create .env file from .env.example
        run: cp .env.example .env

      - name: Upload environment file
        uses: actions/upload-artifact@v3
        with:
          name: env-file
          path: .env
          if-no-files-found: warn
          include-hidden-files: true

  build:
    runs-on: ubuntu-latest
    needs: prepare-env
    steps:
      - uses: actions/checkout@v4

      - name: List files in the workspace
        run: ls -la

      - name: Download environment file
        uses: actions/download-artifact@v3
        with:
          name: env-file
          path: .

      - name: Build app
        run: docker compose build

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Download environment file
        uses: actions/download-artifact@v3
        with:
          name: env-file
          path: .

      - name: Test app
        run: docker compose up user_service_test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4

      - name: Download environment file
        uses: actions/download-artifact@v3
        with:
          name: env-file
          path: .

      - name: deploy app
        run: docker compose up
